//src/lib/security-events.ts

export enum SecurityEventType {
    PASSWORD_CHANGED = "PASSWORD_CHANGED",
    PASSWORD_CHANGE_REQUESTED = "PASSWORD_CHANGE_REQUESTED",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILED = "LOGIN_FAILED",
    LOGIN_NEW_DEVICE = "LOGIN_NEW_DEVICE",
    LOGIN_BLOCKED_REVOKED_DEVICE = "LOGIN_BLOCKED_REVOKED_DEVICE",
    LOGOUT = "LOGOUT",
    DEVICE_DISABLED = "DEVICE_DISABLED",
}