export const actividades = [
    "Abastecimiento y Distribución de Agua",
    "Administración de Consorcios y Gestión de Propiedades",
    "Agencias de Empleo y Recursos Humanos",
    "Alquiler de Autos y Vehículos",
    "Alquiler de Consultorios y Oficinas",
    "Alquiler de Equipos para Eventos",
    "Alquiler de Maquinaria para Construcción",
    "Alquiler de Volquetes y Contenedores",
    "Arreglo y Mantenimiento de Bicicletas",
    "Arreglo y Reparación de Relojes y Joyería",
    "Artes Plásticas y Clases de Arte",
    "Atención Veterinaria y Tienda de Mascotas",
    "Aviación y Servicios Aéreos",
    "Apoyo Escolar y Clases Particulares",
    "Asesoramiento en Finanzas e Inversiones",
    "Asesoría en Imagen y Personal Shopper",
    "Asesoría Legal y Servicios Jurídicos",
    "Automatización y Domótica",
    "Automotores: Compra, Venta y Reparación",
    "Bordado y Personalización de Ropa",
    "Carpintería y Fabricación de Muebles",
    "Cerrajería y Vidriería",
    "Clases de Computación y Alfabetización Digital",
    "Clases de Canto, Baile y Teatro",
    "Clases de Deportes y Entrenamiento Personal",
    "Clases de Instrumentos Musicales",
    "Clases de Meditación y Yoga",
    "Clases de Pilates y Entrenamiento Físico",
    "Clases de Idiomas",
    "Compra y Venta de Antigüedades",
    "Compostaje y Gestión de Residuos",
    "Construcción de Piscinas y Jacuzzis",
    "Consultoría en Desarrollo Organizacional",
    "Contabilidad y Asesoramiento Impositivo",
    "Control de Calidad y Certificaciones",
    "Corte y Confección de Ropa",
    "Courier, Encomiendas y Mensajería",
    "Cursos y Talleres de Manualidades",
    "Cuidado de Pacientes y Asistencia Domiciliaria",
    "Cuidado Infantil y Niñeras",
    "Delivery de Alimentos y Bebidas",
    "Decoración de Interiores y Espacios",
    "Dermatología, Cosmetología y Maquillaje",
    "Desarrollo Web y Creación de Páginas",
    "Destapaciones y Desobstrucción de Caños",
    "Diseño de Interiores y Decoración",
    "Diseño de Moda y Textiles",
    "Diseño y Construcción de Obras Arquitectónicas",
    "Doblaje y Locución",
    "Electricidad: Instalación y Reparación",
    "Enseñanza de Idiomas",
    "Escuelas de Manejo y Cursos de Conducción",
    "Estética, Masajes y Terapias Alternativas",
    "Eventos y Organización de Bodas",
    "Fabricación y Reparación en Herrería",
    "Fabricación y Restauración de Muebles",
    "Ferreterías, Herramientas y Materiales de Construcción",
    "Fletes, Mudanzas y Transporte de Pasajeros",
    "Fotografía y Edición de Imágenes",
    "Franquicias y Oportunidades de Negocio",
    "Fumigación y Control de Plagas",
    "Gestoría del Automotor y Trámites Vehiculares",
    "Guardería y Estética Canina",
    "Imprenta, Servicios Gráficos y Diseño Informático",
    "Instalación y Mantenimiento de Aire Acondicionado",
    "Instalación y Mantenimiento de Alarmas y Sistemas de Seguridad",
    "Instalación y Mantenimiento de Gas y Plomería",
    "Instalación y Reparación de Persianas y Cortinas de Enrollar",
    "Jardinería y Mantenimiento de Espacios Verdes",
    "Kinesiología y Rehabilitación Física",
    "Lavado de Autos y Detailing",
    "Lavandería, Tintorería y Planchado",
    "Librerías y Venta de Material Escolar",
    "Logística y Transporte de Cargas",
    "Marketing Digital y Gestión de Redes Sociales",
    "Mantenimiento y Diseño de Parques y Jardines",
    "Montaje y Mantenimiento de Ascensores",
    "Nutrición y Planificación Dietaria",
    "Odontología y Tratamientos Dentales",
    "Organización y Provisión de Servicios para Fiestas",
    "Paisajismo y Diseño de Jardines",
    "Peluquería, Barbería y Estilismo",
    "Pintura de Casas y Venta de Pinturas",
    "Podología, Pedicura y Cuidado de Manos",
    "Producción Agrícola y Venta de Productos Orgánicos",
    "Producción y Edición Audiovisual",
    "Producción y Venta de Artesanías",
    "Publicidad y Relaciones Públicas",
    "Psicología y Psicopedagogía",
    "Reparación de Aire Acondicionado y Calefacción",
    "Reparación de Cámaras y Equipos Fotográficos",
    "Reparación de Computadoras, Celulares e Impresoras",
    "Reparación de Electrodomésticos",
    "Reparación de Equipos de Gimnasio",
    "Reparación de Heladeras, Lavarropas y Secarropas",
    "Reparación de Instrumentos Musicales",
    "Reparación de Juguetes y Juegos de Mesa",
    "Reparación de Motocicletas y Scooters",
    "Reparación de Ropa y Arreglo de Prendas",
    "Reparación de Televisores, Equipos de Audio y Video",
    "Residencias y Cuidado de Adultos Mayores",
    "Sastrería y Modistería a Medida",
    "Seguros y Planes de Cobertura",
    "Servicios de Catering y Banquetes",
    "Servicios de Diseño Gráfico y Publicitario",
    "Servicios de Impresión 3D",
    "Servicios de Limpieza, Lavandería y Tintorería",
    "Servicios de Mantenimiento para Empresas y Hogares",
    "Servicios de Maquillaje y Peinado para Eventos",
    "Servicios de Reparación de Guitarras y Bajos",
    "Servicios de Traducción e Interpretación",
    "Servicios Jurídicos y Asesoramiento Legal",
    "Tapicería y Restauración de Muebles",
    "Terapia Floral y Tratamientos con Flores de Bach",
    "Terapia Ocupacional y Estimulación Cognitiva",
    "Terapias Holísticas y Alternativas",
    "Textiles, Cortinas y Fundas",
    "Torneado y Mecanizado de Piezas",
    "Tatuajes y Body Piercing",
    "Transporte Escolar y de Pasajeros",
    "Venta e Instalación de Membranas Impermeabilizantes",
    "Venta e Instalación de Pisos y Revestimientos",
    "Venta e Instalación de Toldos y Cerramientos",
    "Venta de Insumos Médicos y Equipamiento de Salud",
    "Venta de Materiales para Construcción",
    "Venta de Plantas y Viveros",
    "Venta y Fabricación de Muebles",
    "Venta, Instalación y Mantenimiento de Techos y Zinguería",
    "Venta, Instalación y Mantenimiento de Ventanas y Cerramientos",
    "Venta, Instalación y Reparación de Equipos Industriales",
    "Venta, Reciclado y Reutilización de Materiales"
];





export const ocupaciones: string[] = [
    // Oficios manuales y técnicos
    "Carpintero",
    "Electricista",
    "Fontanero",
    "Albañil",
    "Mecánico",
    "Pintor",
    "Jardinero",
    "Cerrajero",
    "Sastre",
    "Zapatero",
    "Panadero",
    "Carnicero",
    "Peluquero",
    "Vidriero",
    "Soldador",
    "Escultor",
    "Tapicero",
    "Relojero",
    "Ebanista",
    "Orfebre",
    "Yesero",
    "Herrero",
    "Grabador",
    "Marmolista",
    "Tallador de madera",
    "Encuadernador",
    "Calderero",

    // Transportes y logística
    "Taxista",
    "Chofer",
    "Piloto",
    "Marinero",
    "Controlador aéreo",
    "Despachador de vuelos",
    "Operador de montacargas",
    "Conductor de autobús",
    "Repartidor",
    "Estibador",
    "Transportista",
    "Capitán de barco",
    "Ferrocarrilero",
    "Mecánico de aviones",
    "Despachador de trenes",
    "Conductor de grúa",
    "Coordinador de logística",
    "Cargador de equipaje",
    "Mecánico naval",

    // Hostelería y gastronomía
    "Cocinero",
    "Chef",
    "Mesero",
    "Barista",
    "Pastelero",
    "Sommelier",
    "Bartender",
    "Recepcionista de hotel",
    "Camarero",
    "Conserje de hotel",
    "Guía gastronómico",
    "Maître",
    "Gerente de restaurante",
    "Chef pastelero",
    "Especialista en catering",

    // Comercio y ventas
    "Vendedor",
    "Cajero",
    "Dependiente de tienda",
    "Representante de ventas",
    "Teleoperador",
    "Ejecutivo de cuentas",
    "Supervisor de tienda",
    "Asesor comercial",
    "Especialista en atención al cliente",
    "Gerente de retail",
    "Visual merchandiser",
    "Técnico en comercio exterior",

    // Administración y finanzas
    "Administrador",
    "Contador",
    "Auditor",
    "Asesor financiero",
    "Gestor de recursos humanos",
    "Secretario",
    "Analista financiero",
    "Tesorero",
    "Corredor de bolsa",
    "Analista de riesgos",
    "Especialista en seguros",
    "Gestor de impuestos",
    "Broker financiero",
    "Administrador de propiedades",
    "Perito contable",

    // Derecho y justicia
    "Abogado",
    "Juez",
    "Fiscal",
    "Notario",
    "Procurador",
    "Defensor público",
    "Asesor legal",
    "Criminólogo",
    "Escribano",
    "Mediador",
    "Especialista en derecho penal",
    "Forense",
    "Detective privado",

    // Salud y bienestar
    "Médico",
    "Enfermero",
    "Dentista",
    "Farmacéutico",
    "Fisioterapeuta",
    "Nutricionista",
    "Paramédico",
    "Técnico de laboratorio",
    "Radiólogo",
    "Optometrista",
    "Psiquiatra",
    "Psicólogo",
    "Terapeuta ocupacional",
    "Cuidador de ancianos",
    "Logopeda",
    "Cirujano",
    "Neurólogo",
    "Cardiólogo",
    "Ginecólogo",
    "Pediatra",
    "Médico forense",
    "Médico veterinario",

    // Ingeniería y tecnología
    "Ingeniero civil",
    "Ingeniero mecánico",
    "Ingeniero eléctrico",
    "Ingeniero industrial",
    "Ingeniero en sistemas",
    "Programador",
    "Desarrollador de software",
    "Analista de datos",
    "Administrador de redes",
    "Científico de datos",
    "Ingeniero en inteligencia artificial",
    "Especialista en ciberseguridad",
    "Desarrollador de videojuegos",
    "Ingeniero en telecomunicaciones",
    "Ingeniero aeronáutico",
    "Ingeniero en robótica",
    "Técnico en electrónica",
    "Ingeniero en mecatrónica",

    // Educación y cultura
    "Profesor",
    "Maestro",
    "Pedagogo",
    "Bibliotecario",
    "Investigador",
    "Traductor",
    "Intérprete",
    "Editor",
    "Escritor",
    "Corrector de estilo",
    "Historiador",
    "Arqueólogo",
    "Filósofo",
    "Lingüista",
    "Antropólogo",

    // Comunicación y medios
    "Periodista",
    "Locutor",
    "Fotógrafo",
    "Camarógrafo",
    "Guionista",
    "Productor audiovisual",
    "Community manager",
    "Especialista en marketing digital",
    "Reportero",
    "Redactor de contenidos",
    "Analista de medios",

    // Artes y entretenimiento
    "Actor",
    "Músico",
    "Cantante",
    "Bailarín",
    "Director de cine",
    "Escenógrafo",
    "Diseñador de vestuario",
    "Ilustrador",
    "Dibujante",
    "Animador 3D",
    "Artista plástico",
    "Tatuador",
    "Caricaturista",
    "Magia e ilusionismo",

    // Ciencias
    "Científico",
    "Investigador",
    "Biólogo",
    "Químico",
    "Físico",
    "Matemático",
    "Astrónomo",
    "Geólogo",
    "Meteorólogo",
    "Oceanógrafo",
    "Ecólogo",
    "Bioquímico",
    "Genetista",

    // Seguridad y defensa
    "Policía",
    "Bombero",
    "Militar",
    "Agente de seguridad",
    "Detective privado",
    "Guardia de prisión",
    "Perito forense",
    "Técnico en criminalística",

    // Industria y producción
    "Operario de fábrica",
    "Técnico en mantenimiento",
    "Supervisor de planta",
    "Ingeniero de producción",
    "Inspector de calidad",
    "Operador de maquinaria pesada",
    "Ingeniero en automatización",

    // Agricultura y medio ambiente
    "Agricultor",
    "Ganadero",
    "Pescador",
    "Veterinario",
    "Silvicultor",
    "Ingeniero ambiental",
    "Ecólogo",
    "Técnico en agroindustria",

    // Turismo y recreación
    "Guía turístico",
    "Agente de viajes",
    "Monitor de actividades recreativas",
    "Animador turístico",
    "Gerente de hotel",

    // Servicios y asistencia social
    "Asistente social",
    "Cuidador infantil",
    "Mediador comunitario",
    "Voluntario de ONG",
    "Consejero familiar",
    "Especialista en integración social"
];

export const intereses = [
    "Ajedrez",
    "Actividades al aire libre",
    "Animales y mascotas",
    "Anime y manga",
    "Artes marciales",
    "Astrología y horóscopos",
    "Astronomía y exploración espacial",
    "Automovilismo y deportes de motor",
    "Baile y danza",
    "Barismo y café de especialidad",
    "Béisbol",
    "Bibliotecas y lectura",
    "Bicicletas y ciclismo",
    "Boliche y billar",
    "Camping y senderismo",
    "Caza y pesca",
    "Cine y películas",
    "Cocina y gastronomía",
    "Coleccionismo (monedas, sellos, figuras, etc.)",
    "Comedia y stand-up",
    "Comida saludable y nutrición",
    "Compras y moda",
    "Cosplay y cultura geek",
    "Criptomonedas y blockchain",
    "Cultura asiática y k-pop",
    "Cultura urbana y graffiti",
    "Decoración de interiores",
    "Desarrollo personal y coaching",
    "Deportes extremos",
    "Diseño gráfico y arte digital",
    "Doblaje y locución",
    "Economía y finanzas",
    "Ecosistemas y naturaleza",
    "Ejercicio y fitness",
    "Energías renovables y sostenibilidad",
    "Esoterismo y espiritualidad",
    "Espectáculos y teatro",
    "Esports y videojuegos",
    "Estilo de vida minimalista",
    "Filosofía",
    "Fotografía y edición de imágenes",
    "Fútbol",
    "Fútbol americano",
    "Gastronomía internacional",
    "Historia y arqueología",
    "Idiomas y lingüística",
    "Ilustración y dibujo",
    "Innovación y startups",
    "Instrumentos musicales y composición",
    "Investigación paranormal y misterios",
    "Jardinería y huertos urbanos",
    "Juegos de cartas y de mesa",
    "Literatura y escritura creativa",
    "Maquillaje y estética",
    "Marketing digital y redes sociales",
    "Medios de comunicación y periodismo",
    "Medicina alternativa y bienestar",
    "Moda y tendencias",
    "Motociclismo",
    "Montañismo y escalada",
    "Música y conciertos",
    "Natación",
    "Negocios y emprendimiento",
    "Organización y productividad",
    "Origami y manualidades",
    "Parques temáticos y atracciones",
    "Patinaje sobre ruedas y hielo",
    "Películas y series",
    "Pesca deportiva",
    "Podcast y radio",
    "Política y actualidad",
    "Psicología y desarrollo emocional",
    "Realidad virtual y aumentada",
    "Reciclaje y ecología",
    "Redes sociales y creadores de contenido",
    "Religión y espiritualidad",
    "Robótica y electrónica",
    "Senderismo y montañismo",
    "Series y documentales",
    "Simulación y juegos de rol",
    "Skateboarding y deportes urbanos",
    "Snowboarding y deportes de invierno",
    "Surf y deportes acuáticos",
    "Tatuajes y modificaciones corporales",
    "Tecnología e innovación",
    "Tenis y pádel",
    "Turismo y viajes",
    "Urbex (exploración urbana)",
    "Videojuegos y streaming",
    "Yoga y meditación",
    "Zoología y biología",
];

export const interesesExoticos = [
    "Acrobacias y circo",
    "Acuarios y peces ornamentales",
    "Activismo y voluntariado",
    "Ajedrez y juegos de estrategia",
    "Agricultura y vida rural",
    "Alfarería y cerámica",
    "Alpinismo y expediciones",
    "Aromaterapia y aceites esenciales",
    "Arte conceptual y surrealismo",
    "Astrobiología y vida en otros planetas",
    "Astrofotografía",
    "Automóviles clásicos y restauración",
    "Aventura y deportes extremos",
    "Barcos y navegación",
    "Bebidas artesanales (vino, cerveza, whisky, etc.)",
    "Bioconstrucción y arquitectura sustentable",
    "BMX y freestyle",
    "Boxeo y artes de combate",
    "Caminatas fotográficas",
    "Canotaje y kayak",
    "Carpintería y bricolaje",
    "Ciberseguridad y hacking ético",
    "Ciencia ficción y fantasía",
    "Ciencias naturales y geología",
    "Coleccionismo de objetos raros",
    "Comic books y novelas gráficas",
    "Competencias de resistencia y maratones",
    "Conspiraciones y teorías alternativas",
    "Construcción de modelos a escala",
    "Corte y confección de moda",
    "Criaderos de animales y granjas ecológicas",
    "Criptomonedas y trading",
    "Cultura hacker y tecnología underground",
    "Cultura japonesa y samuráis",
    "Danza folklórica y tradiciones culturales",
    "Defensa personal y krav magá",
    "Demoliciones y construcción",
    "Desarrollo de inteligencia artificial",
    "Diseño de parques y espacios públicos",
    "Diseño de tatuajes y arte corporal",
    "Documentales y biografías",
    "Drones y fotografía aérea",
    "Efectos especiales y maquillaje FX",
    "Energía nuclear y física cuántica",
    "Entretenimiento interactivo y experiencias inmersivas",
    "Estrategia militar y tácticas de guerra",
    "Esquí y snowboard",
    "Exploración submarina y buceo",
    "Feng shui y armonización del hogar",
    "Filatelia y numismática (colección de sellos y monedas)",
    "Filosofía oriental y budismo",
    "Fisioterapia y rehabilitación deportiva",
    "Foros de debate y discusiones filosóficas",
    "Fotografía analógica y cámaras vintage",
    "Gaming competitivo y esports",
    "Genealogía y estudios familiares",
    "Geopolítica y relaciones internacionales",
    "Gimnasia artística y rítmica",
    "Graffiti y arte urbano",
    "Halterofilia y levantamiento de pesas",
    "Hardware y modding de PC",
    "Herbolaria y remedios naturales",
    "Historia alternativa y mitologías",
    "Ilustración digital y arte conceptual",
    "Impresión 3D y modelado digital",
    "Instrumentos exóticos y poco comunes",
    "Investigación paranormal y fenómenos extraños",
    "Juegos de rol en vivo (LARP)",
    "Karate, judo y aikido",
    "Kendō y esgrima japonesa",
    "Lenguaje de señas y comunicación inclusiva",
    "Lucha libre y wrestling",
    "Manejo de drones y robótica aérea",
    "Mapeo y cartografía",
    "Meteorología y estudio del clima",
    "Modelismo ferroviario y trenes en miniatura",
    "Moda vintage y retro",
    "Montaje y diseño de efectos visuales",
    "Motocross y deportes de motor",
    "Mundo submarino y buceo en cavernas",
    "Música clásica y ópera",
    "Música experimental y vanguardista",
    "Música lo-fi y chillout",
    "Navegación astronómica y uso de brújula",
    "Nutrición deportiva y suplementos",
    "Observación de aves y fauna silvestre",
    "Odontología estética y ortodoncia",
    "Operación de maquinaria pesada",
    "Oratoria y habilidades de comunicación",
    "Origami y arte en papel",
    "Paleontología y fósiles",
    "Parkour y freerunning",
    "Perfumería y creación de fragancias",
    "Pintura en acuarela y óleo",
    "Piragüismo y rafting",
    "Pirotecnia y espectáculos de luces",
    "Podcasting y creación de contenido de audio",
    "Política internacional y diplomacia",
    "Programación y desarrollo de software",
    "Psicología forense y criminología",
    "Radiocomunicación y radioaficionados",
    "Realidad virtual y experiencias inmersivas",
    "Recreación medieval y combates históricos",
    "Reciclaje creativo y reutilización de materiales",
    "Redacción y blogs",
    "Reparación y restauración de autos clásicos",
    "Restauración de arte y antigüedades",
    "Robótica y automatización",
    "Rutas gastronómicas y turismo culinario",
    "Senderismo en alta montaña",
    "Simulación de vuelo y aviación",
    "Sitios arqueológicos y ruinas antiguas",
    "Skateboarding y deportes de tabla",
    "Slow travel y turismo ecológico",
    "Stand-up comedy y humor",
    "Stock market y trading financiero",
    "Subastas y compras de coleccionistas",
    "Supervivencia y bushcraft",
    "Tatuajes y modificación corporal",
    "Tecnología espacial y exploración del universo",
    "Tejido y bordado artístico",
    "Terapia con animales y equinoterapia",
    "Tiro con arco y arquería deportiva",
    "Traducción y estudios de lingüística",
    "Turismo de aventura y expediciones extremas",
    "Turismo rural y hospedajes ecológicos",
    "Ufología y avistamientos OVNI",
    "Urbanismo y planificación de ciudades",
    "Viajes en motocicleta y rutas en carretera",
    "Viajes en tren y ferrocarriles históricos",
    "Videojuegos retro y arcade",
    "Vinos y catas de degustación",
    "Volcanología y fenómenos geológicos",
    "Windsurf y kitesurf",
    "Yates y navegación de lujo",
    "Zoología y estudio de especies raras"
];








