import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/custom/navbar";
import Main from "../components/custom/main";
import ClientSessionProvider from "./sessionprovider";
import { GlobalProvider } from "@/context/globalcontext";

export const metadata: Metadata = {
  title: "User Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <GlobalProvider>
          <ClientSessionProvider>
            <Main>
              <Navbar />
              {children}
            </Main>
          </ClientSessionProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
