import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/navbar";
//import { SessionProvider } from "next-auth/react"
import ClientSessionProvider from "./sessionprovider";
import { GlobalProvider } from "@/context/globalcontext";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
export const metadata: Metadata = {
  title: "User Authentication",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={/*`${geistSans.variable} ${geistMono.variable} antialiased`*/""}
      >
        <GlobalProvider>
          <ClientSessionProvider>
            <Navbar />
            {children}
          </ClientSessionProvider>
        </GlobalProvider>


      </body>
    </html>
  );
}
